### ISSUE TITLE
My magister is blocked 

### ISSUE THREAD

**Issue by oscar345** [Yoeori/magister-ical#1]
Since I entered my password and my student number on your site, my magister is being blocked.

**Comment by Yoeori** [comment]
I'm not in high school anymore and thus can't test the system myself. All of the code is quite old and hasn't been worked on for > 1 year.

If you are using: https://school.yoeori.nl/services/calendar/, this is also an old version that doesn't work anymore. It should never make more then 1 request to magister per request on the page (The logs seem to confirm this) but because Magister has changed a lot I don't know how it handles incorrect requests. If you are blocked this is probably only temporarily otherwise you should ask your school to unblock you.

Because the running code isn't working anymore and I can't easily update it I'll deprecate the project, feel free to clone it / fix it and try to run it yourself.
